services:
  - type: web
    name: soundings-explorer
    env: static
    buildCommand: ./build.sh
    staticPublishPath: dist
    envVars: # Environment variables
      - key: VITE_API_BASE_URL
        value: https://sounding-api.onrender.com
